POST http://localhost:3003/api/users
Content-Type:application/json 

{

  "username": "admin",

  "name": "adminjuan",

  "email": "pruebaadministrador@gmail.com",

  "rol": "admin",

  "password": "admin1234"

}
