POST http://localhost:3003/api/users

Content-Type: application/json

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTRkNTAwODllNjM4MmU2ZGUwM2U3MyIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2wiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzU1NjMyOTU2LCJleHAiOjE3NTU2MzY1NTZ9.wJ3E9wEPn4mMw_ps54GvJwooY14GpuVwRTdcopzAk1k

{

  "username": "admin",

  "name": "adminjuan",

  "email": "pruebaadministrador@gmail.com",

  "rol": "admin",

  "password": "admin1234"

}
